### PR TITLE
runlib: wrap Popen in with block to maybe fix #547

### LINKED ISSUE #547: runlib: subprocess cleanup regularly fails on Windows
*This issue was originally described in https://github.com/secure-systems-lab/securesystemslib/issues/337 (includes a bit of troubleshooting). In #544 the relevant code was moved to in-toto, making this an in-toto issue.*

----

**Description of issue or feature request**:

Windows regularly fails to remove a temporary file used in a subprocess. The file is created and opened (in a `with` block) in the parent process, and passed as file handle to a subprocess using the `Popen.stdout` argument. The file is removed (outside of the `with` block) in the parent process after the subprocess has exited.

* File is created and opened (twice, once for parent, once for subprocess):

https://github.com/in-toto/in-toto/blob/fbc1eb053dd39c6d1fb307a60bd2c781e667c931/in_toto/runlib.py#L342-L348

* File is passed to subprocess:

https://github.com/in-toto/in-toto/blob/fbc1eb053dd39c6d1fb307a60bd2c781e667c931/in_toto/runlib.py#L376-L378

* File is removed:

https://github.com/in-toto/in-toto/blob/fbc1eb053dd39c6d1fb307a60bd2c781e667c931/in_toto/runlib.py#L403

Error log from [failing ci run](https://github.com/in-toto/in-toto/actions/runs/4168226378/jobs/7214780020#step:7:809): 
```
======================================================================
ERROR: test_timeout_setting (tests.test_runlib.TestLinkCmdExecTimeoutSetting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\in-toto\in-toto\in_toto\runlib.py", line 393, in _subprocess_run_duplicate_streams
    raise subprocess.TimeoutExpired(cmd, timeout)
subprocess.TimeoutExpired: Command '['D:\\a\\in-toto\\in-toto\\.tox\\py\\Scripts\\python.EXE', '-c', 'while True: pass']' timed out after 0.1 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\in-toto\in-toto\tests\test_runlib.py", line 515, in test_timeout_setting
    in_toto.runlib.execute_link([sys.executable, '-c', 'while True: pass'], True)
  File "D:\a\in-toto\in-toto\in_toto\runlib.py", line 446, in execute_link
    _subprocess_run_duplicate_streams(
  File "D:\a\in-toto\in-toto\in_toto\runlib.py", line 403, in _subprocess_run_duplicate_streams
    os.remove(stdout_name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpd0h6tq_y'

```

### PR DESCRIPTION
**Pull request by lukpueh**
This is a trial-and-error attempt to fix race condition in #547. Using the with statement here makes Popen close the file handles we pass to it on exit.

Given that the file handles we pass have been previously opened by us and in a with block too, I would assume that closing is taken care of already.

But since the race condition is clearly related to file resources not being freed (on Windows), this seems worth a try.

Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

### CODE REVIEW

**Review by adityasaky — APPROVED** [review]

**Comment by adityasaky** [comment]
So it passed here but failed on your fork @lukpueh. https://github.com/lukpueh/in-toto/actions/runs/4940709003/jobs/8832601953. That said I'm not sure which workflow file it's picking up, I'm guessing it's using the CI config from here or on the feature branch as windows is enabled (your `develop` hasn't been updated since 2021).

**Comment by adityasaky** [comment]
Apologies for rebasing @lukpueh. I'm okay to merge this change even though it may not be the fix we were looking for, it seems better than what we currently have to use the handler.

**Comment by lukpueh** [comment]
No need to merge, if it doesn't fix the issue. I'll open a separate PR and add a simple retry. I will also leave a comment about the `with` block.

**Comment by lukpueh** [comment]
> That said I'm not sure which workflow file it's picking up, I'm guessing it's using the CI config from here or on the feature branch as windows is enabled (your develop hasn't been updated since 2021).

Unfortunately, it picked up the right [workflow](https://github.com/lukpueh/in-toto/actions/runs/4940709003/workflow) and   [ref](https://github.com/lukpueh/in-toto/actions/runs/4940709003/jobs/8832601953#step:2:373): e49ba9cb8a1c2f042e27ab46855a046a6b20014b. So this indeed is not the cure.

**Pull request closed without merging**
