### PR TITLE
Add appveyor.yml

### PR DESCRIPTION
**Pull request by vladimir-v-diaz**
**Fixes issue #**:

The issue tracker does not have an issue for this task.

**Description of the changes being introduced by the pull request**:

in-toto currently uses Travis CI for continuous integration under Linux.  The project should also use a CI solution for Windows.  I recommend Appveyor, the only drawback being that a free account for OSS projects is limited to one concurrent build.  Note: Appveyor recently added support for Linux, but it might be faster to use Travis (for Linux) + Appveyor (for Windows) because of Appveyor's limit on build jobs.

This pull request adds a `appveyor.yml` configuration file, which executes in-toto's unit tests under Windows for Python versions 2.7, 3.4, 3.5 and 3.6.

The project maintainers will have to create Appveyor account before they can trigger a build job with this configuration file, which hasn't been fully tested (but it should work).

Note: I tried testing in-toto in a Windows VM and most of the unit tests failures I came across were due to incompatible file path separators.

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

Signed-off-by: Vladimir Diaz \<vladimir.v.diaz@gmail.com>

### CODE REVIEW

**Comment by vladimir-v-diaz** [comment]
The pull request fails the Travis CI check, but it might be due to the unexpected unit test failures outlined in https://github.com/in-toto/in-toto/issues/171.

The unit test failure in https://travis-ci.org/in-toto/in-toto/jobs/382751655 randomly fails in one environment, but passes in another.

**Comment by SantiagoTorres** [comment]
> The unit test failure in https://travis-ci.org/in-toto/in-toto/jobs/382751655 randomly fails in one environment, but passes in another.

This is a known issue, that we've found hard to debug. 

It's probably worth just resetting that job (and keeping the log)

**Comment by vladimir-v-diaz** [comment]
I took the time to investigate issue #171, and suspect that the subprocess call to GPG is returning incomplete data under certain circumstances.  See my reply [here](https://github.com/in-toto/in-toto/issues/171#issuecomment-391476417).

It's difficult to debug since the full exception trace is not printed along with the unit test failure.  Is it possible to tell in-toto to log debug messages to a file?  How do you recommend I do that?  I'd like to see the actual data returned by GPG and the source of the exception.

Another thing I've noticed is that the random unit tests failures occur more often on Travis, but not locally.  I have only encountered this issue once on my local machine.

**Comment by vladimir-v-diaz** [comment]
```Bash
======================================================================
FAIL: test_start_stop (tests.test_in_toto_record.TestInTotoRecordTool)
Test CLI command record start/stop with various arguments.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/in-toto/in-toto/tests/test_in_toto_record.py", line 118, in test_start_stop
    self.assert_cli_sys_exit(["stop"] + args, 0)
  File "/home/travis/build/in-toto/in-toto/tests/common.py", line 79, in assert_cli_sys_exit
    self.assertEqual(raise_ctx.exception.code, status)
AssertionError: 1 != 0
```

Included above is the unit test failure that occurred in the Travis build job.  The output doesn't specify the root cause of the exception, but I am sharing it here for documentation purposes (in case the failed Travis job is restarted later).

**Comment by vladimir-v-diaz** [comment]
> Is it possible to tell in-toto to log debug messages to a file? How do you recommend I do that?

I decided to manually change the StreamHandler() in log.py to FileHandler().  I'm not sure how you normally do it in in-toto.

https://github.com/in-toto/in-toto/blob/ae8ddcdf8850ed47eb68f7d245122787b6b58ebd/in_toto/log.py#L126

Next time I come across a random unit test failure, it'll be easier for me to review the more detailed log messages (and hopefully the root cause of the exception).

**Comment by vladimir-v-diaz** [comment]
Update: This pull request depends on a forthcoming PR that fixes the Windows failures, and [GPG support in Windows](https://github.com/in-toto/in-toto/pull/208).  Testing GPG in Windows might require a edit to the Appveyor config introduced here.  See https://github.com/in-toto/in-toto/pull/208#issuecomment-394756026 for more info. on how GPG can be configured in Appveyor.

**Comment by SantiagoTorres** [comment]
In light of having a windows support PR coming I'll merge this. Thanks @vladimir-v-diaz for this!

**Pull request merged**
