### PR TITLE
Travis-ci: added support for ppc64le

### PR DESCRIPTION
**Pull request by sanjaymsh**
Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

**Fixes issue #**:
Added support for ppc64le build on travis-ci.
**Description of the changes being introduced by the pull request**:
This package is included in the distros for ppc64le - we are trying to make sure that integration into the distros is pain free by making sure they have a clean bill of health from their development community. This simplifies the integration process for ppc64le based distros.
**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

Hi,
I have added support for ppc64le build on travis-ci in the branch . The travis-ci build log can be tracked on the link :https://travis-ci.com/github/sanjaymsh/in-toto/builds/191857083 . I believe it is ready for the final review and merge.
Please have a look on it.

Thanks !!

### CODE REVIEW

**Review by lukpueh — COMMENTED** [review]
Thanks for the PR, @sanjaymsh. I think you could also use Travis matrix expansion and only add something like...
```
arch:
  - amd64
  - ppc64le
```

**Comment by lukpueh** [comment]
Also, the `lint` build probably does not have to run on both architectures, right?

**Comment by sanjaymsh** [comment]
> Also, the `lint` build probably does not have to run on both architectures, right?

Hi @lukpueh , Yes, we can exclude 'lint' build from power.

Thanks !!

**Comment by sanjaymsh** [comment]
> Thanks for the PR, @sanjaymsh. I think you could also use Travis matrix expansion and only add something like...
> 
> ```
> arch:
>   - amd64
>   - ppc64le
> ```

Hi @lukpueh , If i tried first this way itself, but the builds were not generating correctly. Then i added like this.

Thanks !!

**Comment by sanjaymsh** [comment]
Hi @lukpueh, i have removed 'lint' build for ppc64le. 

Thanks !!

**Comment by lukpueh** [comment]
Can't merge because there's a conflict with upstream. I suggest we just close here and enable ppc64le builds when addressing #407.

**Pull request closed without merging**
