### PR TITLE
Fix type for --run-timeout

### PR DESCRIPTION
**Pull request by adityasaky**
Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

**Fixes issue #**: https://github.com/in-toto/in-toto/issues/624#issuecomment-1713248159

**Description of the changes being introduced by the pull request**:

Sets the type of `--run-timeout` to int in the CLI. I poked a little at testing this but the way we're mocking CLI invocations seems to make this difficult?

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by adityasaky** [comment]
@Nikhil52254 thanks for catching this!

I think this should fix the type mismatch, the issue is gone for me. Can you confirm it's gone for you by pulling from this branch? For reference, pip should let you install from a git repo: `pip install git+https://github.com/adityasaky/in-toto@fix-timeout-arg-type`

Note, please use this in a separate test virtualenv or the like.

**Comment by chasen-bettinger** [comment]
@adityasaky My bad, thanks for fix!

**Comment by Nikhil52254** [comment]
@adityasaky Can you share the built distribution file like below. So that i can use in my pipeline. I cannot have a separate venv in my DIND as its a shared runner
 
in_toto-2.1.0-py3-none-any.whl

**Review by SantiagoTorres — APPROVED** [review]

**Comment by Nikhil52254** [comment]
Hi Team i cannot find the newer version in pypi org. Can you confirm when will be released?

image

**Comment by adityasaky** [comment]
Sometime today or tomorrow. :)

> On Sep 13, 2023, at 08:07, Nikhil52254 ***@***.***> wrote:﻿
> Hi Team i cannot find the newer version in pypi org. Can you confirm when will be released?

**Comment by adityasaky** [comment]
https://github.com/in-toto/in-toto/releases/tag/v2.1.1

https://pypi.org/project/in-toto/2.1.1/

This now live, thanks for flagging the bug!

**Comment by Nikhil52254** [comment]
Hi Aditya

I run a make cmd and do a docker build and push i see the intoto run completes but actual docker build does not happen?

$ in-toto-run -v -n step_build -k ~/.docker/trust/private/build-system-key.pem -d in-toto/link-files/ -m xxxx/ -p artifacts/container-sha.txt --run-timeout 1800 -- make dev_build
Running 'step_build'...
Recording materials 'xxxx/'...
Running command 'make dev_build'...
Recording products 'artifacts/container-sha.txt'...
Creating link metadata...
Generating link metadata using Metablock...
Signing link metadata using passed key...
Storing link metadata to 'in-toto/link-files/step_build.xxxx.link'...
$ docker images
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
Cleaning up project directory and file based variables
00:00
Job succeeded

Makefile

```makefile
dev_build:
	docker build -f Dockerfile -t $sampleappFullImageName .

```

But same cmd on pipeline works script

**Pull request merged**
