### PR TITLE
Prepare v1.0.0 release

### PR DESCRIPTION
**Pull request by lukpueh**
### Added
* '-P/--password' (prompt) cli argument for in-toto-run/in-toto-record (#402)
* in-toto-run link command timeout setting (#367)
* API and usage documentation for cryptographic key handling with securesystemslib (#402, #408)
* Artifact recording exclude pattern documentation (#373, #405)
* Test key generation mixin (#402)
* 2021 roadmap document (#381)

### Changed
* Move 'settings' docs to new 'configuration' section and make minor enhancements in structure and content (#405)
* Update tested dependencies (#377, #383, #384, #386, #389, #390,  #394, #397, #398, #400, #404, #406)
* Debian downstream release metadata (#382)

### Removed
* 'util' crypto module in favor of securesystemslib key interfaces (#402)
* Obsolete coveralls.io API call in Travis test builds (#399)

### Fixed
* Minor docs issues (#396, #385, #395)
* pylint 2.6.0 (#387) and lgtm.com (#379) warnings

### CODE REVIEW

**Review by SantiagoTorres — APPROVED** [review]
LGTM.

This being such a big milestone, I'd like to have a couple more eyes/approval though

**Comment by lukpueh** [comment]
FYI, the last missing piecefor 1.0.0 was a straightforward and well-documented cryptographic key interface for in-toto users, which we added (and reviewed) in #402, #408.

**Comment by trishankatdatadog** [comment]
Do we have documentation of parameter substitution anywhere, especially the spec?

**Comment by lukpueh** [comment]
> Do we have documentation of parameter substitution anywhere, especially the spec?

Good question. It seems that with none other than the argument description in `verifylib.in_toto_verify`'s docstring which is also available on [read the docs](https://in-toto.readthedocs.io/en/latest/api.html#supply-chain-verification).

https://github.com/in-toto/in-toto/blob/a1dd78b076c7e37ce43369d089afe059ab787738/in_toto/verifylib.py#L1419-L1421

Judging from the rest of the [related code documentation](https://github.com/in-toto/in-toto/blob/a1dd78b076c7e37ce43369d089afe059ab787738/in_toto/verifylib.py#L259-L261) and the fact that it's not part of the in-toto spec, it looks like this is an experimental feature? What do others think?

**Comment by trishankatdatadog** [comment]
> Judging from the rest of the [related code documentation](https://github.com/in-toto/in-toto/blob/a1dd78b076c7e37ce43369d089afe059ab787738/in_toto/verifylib.py#L259-L261) and the fact that it's not part of the in-toto spec, it looks like this is an experimental feature? What do others think?

I dunno, it's being used in production...

**Review by adityasaky — APPROVED** [review]

**Comment by lukpueh** [comment]
@adityasaky kindly submitted a ticket to add usage docs for parameter substitution (https://github.com/in-toto/in-toto/issues/414). I am all for it, but I don't think we should block 1.0.0 on it. What do others think?

**Comment by adityasaky** [comment]
> I don't think we should block 1.0.0 on it.

I agree. :)

**Pull request merged**
