### PR TITLE
in_toto_verifylib: fix require/disallow queue

### PR DESCRIPTION
**Pull request by SantiagoTorres**
**Fixes issue #**: None

**Description of the changes being introduced by the pull request**:

This reverts commit 21129a6e52ad848fe34e40dcf942bea089c72060 and
replaces the consumed = artifacts_queue with consumed = set(), the
reason as to why is that a require rule passing overwrites all the queue
with a set() call...

**Please verify and check that the pull request fulfills the following
requirements**:

- [x] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [x] Tests have been added for the bug fix or new feature
- [x] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Review by lukpueh — COMMENTED** [review]
Thanks for the fix, @SantiagoTorres! I referenced the PR in the list of artifact rule related PRs (https://github.com/in-toto/docs/issues/4).

What do you think about defining the empty set only once above the if/else cascade? Similar to how we do it in our [in-toto-golang](https://github.com/in-toto/in-toto-golang/blob/09155ed93d3472881d134e21145d1d7f8767d056/in_toto/verifylib.go#L257) (where the compiler forced us to do this right  in the first place).

**Comment by SantiagoTorres** [comment]
I was hesitant to do that just to avoid it to allocate a new `set()` for every iteration. I wonder if what we'd like instead is to declare it as an empty set outside the `for`?

**Comment by lukpueh** [comment]
Okay, fair enough. Not sure I understand your alternative proposition. We can't declare `consumed` outside the loop as it gets overridden by match/create/delete/modify/allow rules. Or did you mean declare an `empty_set = set()` and in disallow/require do something like `consumed = empty_set`?

I think my preferred solution would be one of,
- as it is now,
- what I suggested above (despite the unnecessary allocations), 
- in match/create/delete/modify/allow replace
 `consumed = verify_*_rule(...` with `artifacts_queue -= verify_*_rule(...`,
- modify `verify_disallow_rule` and `verify_require_rule` to return an empty set too and also assign it to `consumed`

**Review by lukpueh — APPROVED** [review]
Let's merge this soon. Let me know what you think of my suggestions (above). If none if it seems preferable we can merge as is.

**Comment by SantiagoTorres** [comment]
Let's do what you suggested above despite the allocations.

**Comment by lukpueh** [comment]
@SantiagoTorres, I took over your branch. And made the small modification we talked about. I hope that's okay? I also fixed the outdated docstring. Can you take a quick look at it and greenlight?

**Comment by SantiagoTorres** [comment]
LGTM. Thanks!

**Pull request merged**
