### PR TITLE
Changing expiration check to match TUF

### PR DESCRIPTION
**Pull request by ShubhikaBhardwaj**
Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

**Fixes issue**: #417 

**Description of the changes being introduced by the pull request**:
Changing `expire_datetime <= datetime.datetime.now(tz.tzutc())`
to `expire_datetime <= datetime.datetime.now(tz.tzutc())` as discussed at #417 
**Please verify and check that the pull request fulfills the following
requirements**:

- ☑ The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- ☑ Tests have been added for the bug fix or new feature
- ☑ Docs have been added for the bug fix or new feature

### CODE REVIEW

**Review by adityasaky — COMMENTED** [review]
Hi @ShubhikaBhardwaj, thanks for the patch! Could you add a test which mocks `datetime.datetime.now` to a known value, set that value to a layout's expiry, and therefore show in_toto_verify passes? See: https://github.com/in-toto/in-toto/blob/develop/tests/test_verifylib.py#L905 for the test where expiry is currently tested.

cc @lukpueh

**Comment by lukpueh** [comment]
Hi @ShubhikaBhardwaj, thanks for the patch! A test would indeed be great. Do you want to provide one?

**Comment by ShubhikaBhardwaj** [comment]
Yes. I can provide a test case as well

**Comment by adityasaky** [comment]
Closing in favour of #616. Thank you for your work on this!

**Pull request closed without merging**
