### PR TITLE
Update Docker images on release or push to master

### PR DESCRIPTION
**Pull request by trishankatdatadog**
Signed-off-by: Trishank Karthik Kuppusamy <trishank.kuppusamy@datadoghq.com>

**Fixes issue #**:

N/A

**Description of the changes being introduced by the pull request**:

Update Docker images on release or push to master.

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by SantiagoTorres** [comment]
so I'll say I *really* like this. although I wonder if we could move it to the docker images repo (or somehow pull the docker images repo and build on top of that or something like that).

Mostly the concern I have is about being able to think about packaging the docker images as a separate entity, although I'm willing to discusss..

**Comment by trishankatdatadog** [comment]
You mean the [Dockerfiles](https://github.com/in-toto/Dockerfiles) repo?

I think it makes sense to consolidate both repos, because these images should be updated and tagged whenever there is a new release of in-toto, no?

**Comment by SantiagoTorres** [comment]
> You mean the Dockerfiles repo?

yes, I was thinking of keeping it separate, although I could go both ways. I do like publishing the containers with a release, although I wonder if it'd be better to have it use the releases we make from upstream repositories instead of blindly making a new container on untrusted infrastructure...

**Comment by trishankatdatadog** [comment]
Up to you guys. In any case, there should be a repeatable process across all sources (e.g., GitHub, PyPI, Docker) for every release we make.

**Comment by SantiagoTorres** [comment]
Hmm, I'm reviewing this PR. I think we discussed on slack we could trigger a build on the dockerfiles repo whenever something happens here, right?

**Comment by lukpueh** [comment]
Closing due to inactivity

**Pull request closed without merging**
