### PR TITLE
Add acknowledgements section to README

### PR DESCRIPTION
**Pull request by lukpueh**
Mention @JustinCappos and link to Secure Systems Lab homepage in acknowledgements section in main README.md.

Do we also want to mention project fundings, like [TUF](https://github.com/theupdateframework/tuf#acknowledgements) does?

### CODE REVIEW

**Comment by vladimir-v-diaz** [comment]
I think you might need to mention NJIT.

**Comment by lukpueh** [comment]
Oh yes, valid point. Thanks Vlad!

**Comment by SantiagoTorres** [comment]
I don't see harm in this, but I think the issue was with the websites, not the README's. We already have them mentioned on [ours](https://in-toto.io).

**Comment by vladimir-v-diaz** [comment]
@JustinCappos's request does specifically say to add a link to the SSL website from each project's website.  However, he also went ahead and edited TUF's README to include one.
https://github.com/theupdateframework/tuf/commit/3f44d99354e9fd0bfd2e8bcde1d8494c6424fbe1

**Pull request merged**
