### PR TITLE
Mention verification does not fail if commands don't align

### PR DESCRIPTION
**Pull request by adityasaky**
**Fixes issue #**: Related to #454 

**Description of the changes being introduced by the pull request**:

Adds to the documentation that failure in command alignment does not mean in-toto verification fails.

**Please verify and check that the pull request fulfills the following
requirements**:

- [ ] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by adityasaky** [comment]
@trishankatdatadog @omerlh

Please let me know if this makes things clearer. :slightly_smiling_face:

Here is the documentation with the change in this PR: https://in-toto--455.org.readthedocs.build/en/455/api.html#supply-chain-verification

**Comment by trishankatdatadog** [comment]
I think you can be clearer. Maybe like a state transition diagram that depicts which states you go into? Don't know if overkill, but pls think about it

**Comment by adityasaky** [comment]
Sorry, I didn't quite get that. What are the different states? As far as I can tell, this particular change only documents that command non-alignment is a warning, and not a failure of verification. Do you mean we should include a graphic for the full verification workflow?

**Comment by trishankatdatadog** [comment]
Yes, which things soft-fail, which don't, and so on. There are many steps involved in the whole process. It's not clear how things can go wrong when and in which way.

**Comment by omerlh** [comment]
This [comment](https://github.com/in-toto/in-toto/issues/454#issuecomment-849195031) really help me reason about the why - so maybe worth mentioning it.

**Comment by adityasaky** [comment]
@omerlh I've added a reference to the specification which has that quote.

@trishankatdatadog as far as I can tell, command alignment is the only part of the verification workflow where failure results in a warning rather than a full in-toto verification failure. However, I think a graphic could be useful, also to highlight nuances about how failure of sublayouts do not necessarily lead to in-toto verification failure, but rather are subject to threshold constraints and so on. I'm currently leaning towards merging this change and opening a ticket for the workflow graphics because I think it could be a helpful task for someone new looking to better understand the verification workflow. Thoughts?

**Comment by SantiagoTorres** [comment]
LGTM. Thank you! I'll merge this and re-open 454 to drop a comment soon-ish. Thank you for the discussion @omerlh, @adityasaky, @trishankatdatadog !

**Pull request merged**
