### PR TITLE
Fix spec pdf link

### PR DESCRIPTION
**Pull request by ShikherVerma**

### CODE REVIEW

**Comment by SantiagoTorres** [comment]
👍 

I think you can sneak the other changes here too (the fixes to the urls and whatnot).

Thanks!

**Comment by lukpueh** [comment]
Thanks Shikher, please always provide a description for your PRs. I guess for a minor one like this, a one-liner would be sufficient.

**Comment by ShikherVerma** [comment]
@lukpueh yeah sure.

@SantiagoTorres that url fix was on other repo if that's what you meant.

**Comment by ShikherVerma** [comment]
Yaay !!

**Pull request merged**
