### PR TITLE
Making metadata print pretty

### PR DESCRIPTION
**Pull request by ShubhikaBhardwaj**
Please fill in the fields below to submit a pull request.  The more information
that is provided, the better.

**Fixes issue #18 **:

**Description of the changes being introduced by the pull request**:
- Showing metadata in a logically structured and human friendly way as well.
- Order fields logically instead of alphabetically
- Strip keys and signatures in all the modules present

**Please verify and check that the pull request fulfills the following
requirements**:

- [☑] The code follows the [Code Style Guidelines](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines)
- [☑] Tests have been added for the bug fix or new feature
- [☑] Docs have been added for the bug fix or new feature

### CODE REVIEW

**Comment by lukpueh** [comment]
Thanks for the patch, @ShubhikaBhardwaj! Is this PR ready for review? If not, please state so somewhere in the PR description or in a comment. You can also [mark the PR as a draft ](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests).

**Comment by lukpueh** [comment]
Hi @ShubhikaBhardwaj, do you intend to continue your work here? Otherwise, I suggest to close the PR.

**Comment by ShubhikaBhardwaj** [comment]
Hi @lukpueh  
This PR is ready for review. Waiting for your feedback

**Comment by adityasaky** [comment]
I took a quick look at this PR. I think there's been a slight misunderstanding of the original issue but it shouldn't be too hard to fix. Your patch, as it's written here, tries to remove signatures and sort metadata keys in the actual metadata itself. This is not the intent of the original ticket, because we actually need that information to _verify_ the metadata. Instead, what the PR should do is present a separate interface for the user to load some in-toto metadata and gain a higher level, human friendly representation of the information in that metadata.

You'll notice that if you update the PR to fix the use of `strip` where it can't be used, tests will still fail because at the end of the day we (and so our tests) do care about the signatures and other key information, just perhaps not when we want to examine the metadata for higher level reasoning. Moving some of the same changes into a separate interface is probably a good start!

Finally, I think your commit from #545 snuck in here as well, but that's a minor nit. :smile:

**Comment by lukpueh** [comment]
Closing due to inactivity...

**Pull request closed without merging**
